<?php

declare(strict_types = 1);

namespace Zend\DI\Config\Tool;

class AutowiresConfigDumper
{

    const CONFIG_TEMPLATE = <<<EOC
<?php

/**
 * This file generated by %s.
 * Generated %s
 */

return %s;

EOC;

    const AUTOWIRES = 'autowires';

    public function createDependencyConfig(array $config, string $className): array
    {
        if (! isset($config['dependencies'])) {
            $config['dependencies'] = [];
        }

        if (! is_array($config['dependencies'])) {
            throw new \InvalidArgumentException(
                'Configuration dependencies key must be an array'
            );
        }

        $config['dependencies'] = $this->addAutowires($config['dependencies'], $className);

        return $config;
    }

    public function dumpConfigFile(array $config): string
    {
        $prepared = $this->prepareConfig($config);

        return sprintf(
            self::CONFIG_TEMPLATE,
            get_class($this),
            date('Y-m-d H:i:s'),
            $prepared
        );
    }

    private function addAutowires(array $dependencies, string $entry): array
    {
        if (! isset($dependencies[$this::AUTOWIRES]) || ! is_array($dependencies[$this::AUTOWIRES])) {
            $dependencies[$this::AUTOWIRES] = [];
        }

        // Add the class name as an entry to the autowires configuration
        if (! in_array($entry, $dependencies[$this::AUTOWIRES], true)) {
            $dependencies[$this::AUTOWIRES][] = $entry;
        }

        return $dependencies;
    }

    private function prepareConfig(array $config, int $indentLevel = 1): string
    {
        $indent = str_repeat(' ', $indentLevel * 4);
        $entries = [];
        foreach ($config as $key => $value) {
            $key = $this->createConfigKey($key);
            $entries[] = sprintf(
                '%s%s%s,',
                $indent,
                $key ? sprintf('%s => ', $key) : '',
                $this->createConfigValue($value, $indentLevel)
            );
        }

        $outerIndent = str_repeat(' ', ($indentLevel - 1) * 4);

        return sprintf("[\n%s\n%s]", implode("\n", $entries), $outerIndent);
    }

    private function createConfigKey($key):? string
    {
        if (is_string($key) && class_exists($key)) {
            return sprintf('\\%s::class', $key);
        }

        if (is_int($key)) {
            return null;
        }

        return sprintf("'%s'", $key);
    }

    private function createConfigValue($value, int $indentLevel): string
    {
        if (is_array($value)) {
            return $this->prepareConfig($value, $indentLevel + 1);
        }

        if (is_string($value) && class_exists($value)) {
            return sprintf('\\%s::class', $value);
        }

        return var_export($value, true);
    }
}
